### ISSUE TITLE
make this nice piece of code loadable via quicklisp

### ISSUE THREAD

**Issue by zekzekus** [evrim/core-server#2]
in core-server project there are many useful and excellent tools, utilities, frameworks. also the core-server itself is a nice piece of shit.

if we want more people to use it, develop it we MUST have it in the quicklisp release system.

let's discuss the technical issues and prepare a roadmap to accomplish this.

**Comment by evrim** [comment]
We've been discussing it here yesterday,

https://groups.google.com/forum/?fromgroups#!topic/comp.lang.lisp/9tlFQK5j_Lo

The main problem is not just pulling the repos, but making a layout for the server. It's just like apache, you have to run make install to be able run the server. 

For the quick stuff, i'll change the name of the arnesi package to something else. Yet changing the system name does not imply the name of the package will be changed. I am not sure now to enable _conflicts_ in quicklisp.

**Comment by evrim** [comment]
Ok, i've changed the system name to arnesi+.

**Comment by aycanirican** [comment]
I think installation with quicklisp is not important for core server atm. Because its very easy to install it via core-server-installer for a lisp developer and the installation frequency for each developer is near 1.

**Comment by zekzekus** [comment]
I agree that it is easy to install with its own script but quicklisp availability is important to make more developers aware of your project. Also all dependencies except arnesi can be obtained via quicklisp. At last it is not mandatory for success but important for popularity

**Comment by evrim** [comment]
https://groups.google.com/forum/?fromgroups#!topic/comp.lang.lisp/9tlFQK5j_Lo

won't fix, sorry.
